updated selenium ci workflow file

diff --git a/.github/workflows/Selenium_CI.yml b/.github/workflows/Selenium_CI.yml
--- a/.github/workflows/Selenium_CI.yml
+++ b/.github/workflows/Selenium_CI.yml
@@ -1,39 +1,45 @@
 # This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Python application
+name: selenium-python
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ '**' ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ '**' ]
 
-permissions:
-  contents: read
+
+permissions: # This is where we set permissions for the workflow specifically to wrtie junit results
+  contents: write 
+  checks: write
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python 3.12
-      uses: actions/setup-python@v3
+    - uses: actions/checkout@v2 # Check the code in the respository
+
+    - name: Set up Python
+      uses: actions/setup-python@v2 # Set up the python environment
       with:
-        python-version: "3.12"
+        python-version: 3.12
+
     - name: Install dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-    - name: Lint with flake8
+        python3 -m pip install --upgrade pip 
+        pip install pytest pytest-cov pytest_bdd # install requred testing dependencies
+
+    - name: Run tests with coverage
       run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest
-      run: |
-        python3 -m pytest -v
+        python -m pytest --verbose --junitxml=report.xml # create junit xml report with pytest
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3 # use this action to publish the junit report
+      if : success() || failure() # Ensure to publish the report regardless of any failures in previous steps in the workflow
+      with:
+        report_paths: '**/junit.xml' # path the junit report
+        detailed_summary: true # provide a detailed summary of the test results
+        include_passed: true # include passed tests in the report
+  
