Upated workflow file to include selenium package

diff --git a/.github/workflows/Selenium_CI.yml b/.github/workflows/Selenium_CI.yml
--- a/.github/workflows/Selenium_CI.yml
+++ b/.github/workflows/Selenium_CI.yml
@@ -1,4 +1,4 @@
-# This workflow will run the tests with pytest and generate a test unit report
+# This workflow will run the tests with pytest and generate a test unit report
 
 name: selenium-python
 
@@ -9,7 +9,7 @@ on:
     branches: [ '**' ]
 
 
-permissions: # This is where we set permissions for the workflow specifically to wrtie junit results
+permissions: # This is where we set permissions for the workflow specifically to write junit results
   contents: write 
   checks: write
 
@@ -18,7 +18,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2 # Check the code in the respository
+    - uses: actions/checkout@v2 # Check the code in the repository
 
     - name: Set up Python
       uses: actions/setup-python@v2 # Set up the python environment
@@ -28,7 +28,7 @@ jobs:
     - name: Install dependencies
       run: |
         python3 -m pip install --upgrade pip 
-        pip install pytest pytest-cov pytest_bdd # install requred testing dependencies
+        pip install pytest pytest-cov pytest_bdd selenium # Updated to include 'selenium'
 
     - name: Run tests with coverage
       run: |
@@ -36,9 +36,8 @@ jobs:
 
     - name: Publish Test Report
       uses: mikepenz/action-junit-report@v3 # use this action to publish the junit report
-      if : success() || failure() # Ensure to publish the report regardless of any failures in previous steps in the workflow
+      if: success() || failure() # Ensure to publish the report regardless of any failures in previous steps in the workflow
       with:
-        report_paths: '**/junit.xml' # path the junit report
+        report_paths: '**/junit.xml' # path to the junit report
         detailed_summary: true # provide a detailed summary of the test results
         include_passed: true # include passed tests in the report
-  
